steps:
  - id: Build image
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/tranquility-base-images/$_IMAGE_NAME-$BRANCH_NAME:latest', '.']

#  - id: Push image
#    name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/tranquility-base-images/$_IMAGE_NAME-$BRANCH_NAME:latest']

#  - id: Label image
#    name: 'gcr.io/cloud-builders/gcloud'
#    waitFor:
#      - Build image
#    args: ['compute', 'images', 'update', '$_IMAGE_NAME-$BRANCH_NAME:latest','--update-labels','git_repo=$REPO_NAME,git_commit=$COMMIT_SHA,git_branch=$BRANCH_NAME','--project=$PROJECT_ID']
#
#  - id: Tag image
#    name: 'gcr.io/cloud-builders/gcloud'
#    waitFor:
#      - Build image
#    args: ['container', 'images', 'add-tag', '$_IMAGE_NAME-$BRANCH_NAME:latest','$_IMAGE_NAME-$BRANCH_NAME:$TAG_NAME']
#
#  - id: Grant access to image
#    name: 'gcr.io/cloud-builders/gcloud'
#    waitFor:
#      - Label image
#    args: ['compute', 'images', 'add-iam-policy-binding', '$_IMAGE_NAME-$BRANCH_NAME:latest','--member=$_IMAGE_MEMBER','--role=$_IMAGE_ROLE']

substitutions:
  _IMAGE_NAME: "tb-gcp-dac"
#  _IMAGE_FAMILY: tb-tr-debian-9
#  _IMAGE_ZONE: europe-west2
  _IMAGE_MEMBER: allAuthenticatedUsers
  _IMAGE_ROLE: roles/compute.imageUser
#  _TESTS_DIR: tb-test/scripts
#  _TEST_INSTANCE_ZONE: europe-west2
images: [
    'gcr.io/tranquility-base-images/$_IMAGE_NAME-$BRANCH_NAME:latest'
]
