steps:
  #  - id: Build image
  #    name: 'gcr.io/cloud-builders/docker'
  #    args: [ 'build', '-t', 'gcr.io/tranquility-base-images/$_IMAGE_NAME-$BRANCH_NAME:latest', '.' ]
  #
  #  - id: Push image
  #    name: 'gcr.io/cloud-builders/docker'
  #    waitFor:
  #      - Build image
  #    args: [ 'push', 'gcr.io/tranquility-base-images/$_IMAGE_NAME-$BRANCH_NAME:latest' ]

  - id: Build image
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME-$BRANCH_NAME', '.' ]

  - id: Push image
    name: 'gcr.io/cloud-builders/docker'
    waitFor:
      - Build image
    args: [ 'push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME-$BRANCH_NAME' ]

  - id: Tag image
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor:
      - Push image
    args: ['container', 'images', 'add-tag', '$_IMAGE_NAME-$BRANCH_NAME','$_IMAGE_NAME-$BRANCH_NAME:$TAG_NAME']


substitutions:
  _IMAGE_NAME: "tb-gcp-dac"
  _IMAGE_MEMBER: allAuthenticatedUsers
  _IMAGE_ROLE: roles/compute.imageUser
images: [
    'gcr.io/tranquility-base-images/$_IMAGE_NAME-$BRANCH_NAME:latest'
  #    'gcr.io/$PROJECT_ID/$_IMAGE_NAME-$BRANCH_NAME:latest'
]
