FROM python:3.6
RUN apt-get update && apt-get install -y --no-install-recommends dos2unix=7.4.0-1 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /srv
COPY mocks/mock_gcp_dac/. .
COPY tb_common/. tb_common
COPY openapi.yml .
RUN pip install -r ./requirements.txt
RUN dos2unix app_docker.sh
RUN ["chmod", "+x", "./app_docker.sh"]
EXPOSE 3000
CMD ["/bin/bash", "./app_docker.sh"]
