apiVersion: v1
kind: Service
metadata:
  name: gcpdac
spec:
  ports:
    - port: 80
      targetPort: 3100
      name: http
    - port: 443
      targetPort: 3100
      name: https
  selector:
    app: gcpdac
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcpdac-v1
  labels:
    app: gcpdac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcpdac
  template:
    metadata:
      labels:
        app: gcpdac
        version: v1
    spec:
      containers:
        - name: gcpdac
          image: gcr.io/tranquility-base-images/tb-gcp-dac:local
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /app/ec-config.yaml
              subPath: ec-config.yaml
            - name: google-cloud-key
              mountPath: /credentials.json
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/ec-service-account-config.json
            - name: CELERY_BROKER_URL
              value: redis://redis:6379
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379

        - name: redis
          image: redis:alpine

        - name: gcpdacworker
          image: gcr.io/tranquility-base-images/tb-gcp-dac:local
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          command: ["celery -E -A celery_worker worker --loglevel=info"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /app/ec-config.yaml
              subPath: ec-config.yaml
            - name: google-cloud-key
              mountPath: /credentials.json
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /credentials.json
            - name: CELERY_BROKER_URL
              value: redis://redis:6379
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379

      volumes:
        - name: config-volume
          configMap:
            name: ec-config
        - name: google-cloud-key
          hostPath:
            path: credentials.json
#            path: C:\dev\tb-gcp-dac\credentials.json
#          secret:
#            secretName: ec-service-account