FROM google/cloud-sdk:298.0.0
MAINTAINER "GFT"


# ==== Arguments ====
ARG gcpdac_src=src/main/python/tranquilitybase/gcpdac
ARG common_src=src/main/python/tranquilitybase/lib/common
ARG test_src=src/test/gcpdac_tests/unit
ARG bash_src=src/main/bash
ARG build_src=build/


# ==== Unix ====
RUN apt-get update \
 && apt-get install unzip=6.0-25 wget=1.20.1-1.1 dos2unix=7.4.0-1 nano=3.2-3 \
 -y --no-install-recommends \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1


# ==== python ====
WORKDIR /app
COPY ${gcpdac_src} ${gcpdac_src}
COPY ${common_src} ${common_src}
COPY ${test_src} ${test_src}
COPY ${bash_src} ${bash_src}
COPY ${build_src} ${build_src}
RUN pip install -r ${gcpdac_src}/requirements.txt

