FROM google/cloud-sdk:298.0.0
MAINTAINER "GFT"


# ==== Arguments ====
ARG src_main_python=src/main/python/
ARG src_test_python=src/test/python/
ARG src_main_bash=src/main/bash
ARG build=build/


# ==== Unix ====
RUN apt-get update \
 && apt-get install unzip=6.0-25 wget=1.20.1-1.1 dos2unix=7.4.0-1 nano=3.2-3 \
 -y --no-install-recommends \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1


# ==== python ====
WORKDIR /app
COPY ${src_main_python} ${src_main_python}
COPY ${src_test_python} ${src_test_python}
COPY ${src_main_bash} ${src_main_bash}
COPY ${build} ${build}
RUN pip install -r ${src_main_python}/tranquilitybase/requirements.txt

